# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tokenring.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftokenring.proto\x12\ttokenring\"\x14\n\x05Token\x12\x0b\n\x03num\x18\x01 \x01(\x04\"\x06\n\x04Void28\n\tTokenring\x12+\n\x04Ring\x12\x10.tokenring.Token\x1a\x0f.tokenring.Void\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tokenring_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOKEN._serialized_start=30
  _TOKEN._serialized_end=50
  _VOID._serialized_start=52
  _VOID._serialized_end=58
  _TOKENRING._serialized_start=60
  _TOKENRING._serialized_end=116
# @@protoc_insertion_point(module_scope)
