# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multicast.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmulticast.proto\x12\tmulticast\x1a\x1bgoogle/protobuf/empty.proto\"z\n\x10MulticastMessage\x12\x15\n\rlamport_clock\x18\x01 \x01(\r\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x1d\n\x04kind\x18\x03 \x01(\x0e\x32\x0f.multicast.Kind\x12\x14\n\x07\x63ontent\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_content*)\n\x04Kind\x12\x0b\n\x07\x44\x45\x46\x41ULT\x10\x00\x12\x0b\n\x07MESSAGE\x10\x01\x12\x07\n\x03\x41\x43K\x10\x02\x32\x9b\x01\n\x10MulticastService\x12\x45\n\x0eReceiveMessage\x12\x1b.multicast.MulticastMessage\x1a\x16.google.protobuf.Empty\x12@\n\x04Test\x12\x1b.multicast.MulticastMessage\x1a\x1b.multicast.MulticastMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'multicast_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KIND._serialized_start=183
  _KIND._serialized_end=224
  _MULTICASTMESSAGE._serialized_start=59
  _MULTICASTMESSAGE._serialized_end=181
  _MULTICASTSERVICE._serialized_start=227
  _MULTICASTSERVICE._serialized_end=382
# @@protoc_insertion_point(module_scope)
