# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import multicast_pb2 as multicast__pb2


class MulticastServiceStub(object):
    """The multicast service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveMessage = channel.unary_unary(
                '/multicast.MulticastService/ReceiveMessage',
                request_serializer=multicast__pb2.MulticastMessage.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Test = channel.unary_unary(
                '/multicast.MulticastService/Test',
                request_serializer=multicast__pb2.MulticastMessage.SerializeToString,
                response_deserializer=multicast__pb2.MulticastMessage.FromString,
                )


class MulticastServiceServicer(object):
    """The multicast service.
    """

    def ReceiveMessage(self, request, context):
        """Receives a multicast message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Test(self, request, context):
        """Test multiple connections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MulticastServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveMessage,
                    request_deserializer=multicast__pb2.MulticastMessage.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=multicast__pb2.MulticastMessage.FromString,
                    response_serializer=multicast__pb2.MulticastMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multicast.MulticastService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MulticastService(object):
    """The multicast service.
    """

    @staticmethod
    def ReceiveMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multicast.MulticastService/ReceiveMessage',
            multicast__pb2.MulticastMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/multicast.MulticastService/Test',
            multicast__pb2.MulticastMessage.SerializeToString,
            multicast__pb2.MulticastMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
