# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gossiping_pb2 as gossiping__pb2


class GossipingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/gossiping.Gossiping/Register',
                request_serializer=gossiping__pb2.Reg.SerializeToString,
                response_deserializer=gossiping__pb2.Reg.FromString,
                )
        self.LocalRegister = channel.unary_unary(
                '/gossiping.Gossiping/LocalRegister',
                request_serializer=gossiping__pb2.Reg.SerializeToString,
                response_deserializer=gossiping__pb2.Void.FromString,
                )
        self.Dessiminate = channel.unary_unary(
                '/gossiping.Gossiping/Dessiminate',
                request_serializer=gossiping__pb2.Data.SerializeToString,
                response_deserializer=gossiping__pb2.Data.FromString,
                )
        self.LocalDict = channel.unary_unary(
                '/gossiping.Gossiping/LocalDict',
                request_serializer=gossiping__pb2.Data.SerializeToString,
                response_deserializer=gossiping__pb2.Void.FromString,
                )


class GossipingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dessiminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalDict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GossipingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=gossiping__pb2.Reg.FromString,
                    response_serializer=gossiping__pb2.Reg.SerializeToString,
            ),
            'LocalRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalRegister,
                    request_deserializer=gossiping__pb2.Reg.FromString,
                    response_serializer=gossiping__pb2.Void.SerializeToString,
            ),
            'Dessiminate': grpc.unary_unary_rpc_method_handler(
                    servicer.Dessiminate,
                    request_deserializer=gossiping__pb2.Data.FromString,
                    response_serializer=gossiping__pb2.Data.SerializeToString,
            ),
            'LocalDict': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalDict,
                    request_deserializer=gossiping__pb2.Data.FromString,
                    response_serializer=gossiping__pb2.Void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gossiping.Gossiping', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gossiping(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossiping.Gossiping/Register',
            gossiping__pb2.Reg.SerializeToString,
            gossiping__pb2.Reg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LocalRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossiping.Gossiping/LocalRegister',
            gossiping__pb2.Reg.SerializeToString,
            gossiping__pb2.Void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Dessiminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossiping.Gossiping/Dessiminate',
            gossiping__pb2.Data.SerializeToString,
            gossiping__pb2.Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LocalDict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gossiping.Gossiping/LocalDict',
            gossiping__pb2.Data.SerializeToString,
            gossiping__pb2.Void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
