# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gossiping.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgossiping.proto\x12\tgossiping\"\x11\n\x03Reg\x12\n\n\x02ip\x18\x01 \x01(\t\"&\n\x04\x44\x61ta\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08nullable\x18\x02 \x01(\x08\"\x06\n\x04Void2\xd1\x01\n\tGossiping\x12,\n\x08Register\x12\x0e.gossiping.Reg\x1a\x0e.gossiping.Reg\"\x00\x12\x32\n\rLocalRegister\x12\x0e.gossiping.Reg\x1a\x0f.gossiping.Void\"\x00\x12\x31\n\x0b\x44\x65ssiminate\x12\x0f.gossiping.Data\x1a\x0f.gossiping.Data\"\x00\x12/\n\tLocalDict\x12\x0f.gossiping.Data\x1a\x0f.gossiping.Void\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gossiping_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REG._serialized_start=30
  _REG._serialized_end=47
  _DATA._serialized_start=49
  _DATA._serialized_end=87
  _VOID._serialized_start=89
  _VOID._serialized_end=95
  _GOSSIPING._serialized_start=98
  _GOSSIPING._serialized_end=307
# @@protoc_insertion_point(module_scope)
